# Generated by Django 3.1.2 on 2020-10-09 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20201008_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
