# Generated by Django 3.1.2 on 2020-11-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_account_is_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
