# Generated by Django 3.1.2 on 2020-10-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallbanner',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smallbanner',
            name='sub_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smallbanner',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
