# Generated by Django 3.1.2 on 2020-10-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20201014_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='smallbanner',
            name='heading',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
