# Generated by Django 3.1.2 on 2020-11-29 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0025_merge_20201127_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('referID', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('ESEWA', 'ESEWA'), ('KHALTI', 'KHALTI')], max_length=15)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.order')),
            ],
        ),
    ]
