# Generated by Django 3.1.2 on 2020-11-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_productname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
