# Generated by Django 3.1.2 on 2020-11-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_productname',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='quantity',
        ),
    ]
