# Generated by Django 3.1.2 on 2020-10-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='date_of_establishment',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='website',
            field=models.URLField(max_length=50, null=True),
        ),
    ]
