# Generated by Django 3.1.2 on 2020-10-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerAccount', '0002_auto_20201012_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selleraccount',
            name='shop_name',
        ),
        migrations.AddField(
            model_name='selleraccount',
            name='business_type',
            field=models.CharField(blank=True, choices=[('Sole Proprietorship', 'Sole Proprietorship'), ('Partnership', 'Partnership'), ('Corporation', 'Corporation'), ('Shop', 'Shop')], max_length=30, null=True),
        ),
    ]
