# Generated by Django 3.1.2 on 2020-12-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerAccount', '0004_contact_seller_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_seller_account',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
