# Generated by Django 3.1.2 on 2020-12-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerAccount', '0005_contact_seller_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_seller_account',
            name='business_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
