# Generated by Django 3.1.2 on 2021-02-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellerAccount', '0008_selleraccount_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_seller_account',
            name='brand_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
