# Generated by Django 3.1.2 on 2021-02-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellerAccount', '0008_auto_20210210_1631'),
        ('SellerAccount', '0009_contact_seller_account_brand_name'),
    ]

    operations = [
    ]
