# Generated by Django 3.1.2 on 2021-02-10 11:22

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('Cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='body',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
