# Generated by Django 3.1.2 on 2021-02-10 13:19

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('Cms', '0002_auto_20210210_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyAndPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', djrichtextfield.models.RichTextField()),
            ],
        ),
    ]
