# Generated by Django 3.1.2 on 2021-02-11 15:18

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('Cms', '0003_privacyandpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', djrichtextfield.models.RichTextField()),
            ],
        ),
    ]
