# Generated by Django 3.1.2 on 2021-02-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cms', '0003_privacyandpolicy'),
        ('Cms', '0003_termsandconditions'),
    ]

    operations = [
    ]
