# Generated by Django 3.1.2 on 2021-02-11 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cms', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='offer',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
