# Generated by Django 3.1.2 on 2021-02-14 05:16

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('Cms', '0004_merge_20210211_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('body', djrichtextfield.models.RichTextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='banner_front')),
            ],
        ),
    ]
