# Generated by Django 3.1.2 on 2021-02-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cms', '0005_banner_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_front'),
        ),
    ]
