# Generated by Django 3.1.2 on 2021-02-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cms', '0006_banner_profile_image'),
        ('Cms', '0005_banner'),
    ]

    operations = [
    ]
