# Generated by Django 3.1.2 on 2020-10-18 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SellerAccount', '0003_auto_20201013_1219'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='SellerAccount.selleraccount'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
                ('seller_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SellerAccount.selleraccount')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
