# Generated by Django 3.1.2 on 2020-10-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_wishlist_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='liked',
            field=models.BooleanField(default=True),
        ),
    ]
