# Generated by Django 3.1.2 on 2020-10-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_sellerprofile'),
        ('Products', '0012_auto_20201022_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, to='Profile.Profile'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='liked',
            field=models.CharField(choices=[('Wish', 'Wish'), ('Unwish', 'unwish')], default='Unwish', max_length=15),
        ),
    ]
