# Generated by Django 3.1.2 on 2020-10-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_sellerprofile'),
        ('Products', '0013_auto_20201028_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to='Profile.Profile'),
        ),
    ]
