# Generated by Django 3.1.2 on 2020-10-28 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SellerAccount', '0003_auto_20201013_1219'),
        ('Products', '0014_auto_20201028_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_account', to='SellerAccount.selleraccount'),
        ),
    ]
