# Generated by Django 3.1.2 on 2020-11-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_auto_20201028_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='liked',
        ),
    ]
