# Generated by Django 3.1.2 on 2020-11-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0019_auto_20201119_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(related_name='orderitem', to='Products.OrderItem'),
        ),
    ]
