# Generated by Django 3.1.2 on 2020-11-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0024_product_date'),
        ('Products', '0023_product_date'),
    ]

    operations = [
    ]
