# Generated by Django 3.1.2 on 2020-11-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0025_merge_20201127_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
