# Generated by Django 3.1.2 on 2020-12-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0027_auto_20201201_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingadress',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='email address'),
        ),
    ]
