# Generated by Django 3.1.2 on 2020-12-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0028_auto_20201203_1810'),
        ('Products', '0028_auto_20201203_1500'),
    ]

    operations = [
    ]
