# Generated by Django 3.1.2 on 2020-12-07 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0031_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maincategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.maincategory'),
        ),
    ]
