# Generated by Django 3.1.2 on 2020-12-07 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0032_product_maincategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='maincategory',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.subcategory'),
        ),
    ]
