# Generated by Django 3.1.2 on 2021-02-18 09:26

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0033_auto_20201207_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_details',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
